AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'examples/**/*'
    - 'spec/**/*'
    - 'test/**/*'

# Disable noisy cops for this project
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Max: 200

Gemspec/OrderedDependencies:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
